name: Update daily

on:
  schedule:
    - cron: "0 17 * * *"  # Runs daily at 17:00 UTC
  workflow_dispatch:

jobs:
  alter_repo:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show current branch
        run: git branch --show-current

      - name: Set up Git identity
        run: |
          git config --global user.name "Lizard31"
          git config --global user.email "bordianutudor@gmail.com"

      - name: Extract target number of commits from seed.txt
        id: extract_seed
        run: |
          NUMBER=$(grep $(date +%F) seed.txt | cut -d' ' -f2)
          echo "TARGET_COMMITS=$NUMBER" >> $GITHUB_ENV
          echo "Target commits: $NUMBER"

      - name: Fetch commits from GitHub activity
        id: fetch_activity
        env:
          GH_TOKEN: ${{ secrets.JUNIOR_TOKEN }}
        run: |
          TODAY=$(date +%Y-%m-%d)

          echo "Fetching current user via GH_TOKEN..."
          USERNAME=$(gh api user --jq .login)
          echo "Authenticated as $USERNAME"

          echo "Fetching push events for $TODAY..."
          COMMIT_COUNT=$(gh api "/users/$USERNAME/events" | jq --arg today "$TODAY" '
            map(select(.type == "PushEvent" and .created_at[:10] == $today))
            | map(.payload.commits) | flatten | length
          ')
          
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Found $COMMIT_COUNT commits today"

      - name: Create missing commits
        id: create_missing
        env:
          TARGET_COMMITS: ${{ env.TARGET_COMMITS }}
          COMMIT_COUNT: ${{ env.COMMIT_COUNT }}
        run: |
          echo "Creating missing commits if needed..."
          MISSING=$((TARGET_COMMITS - COMMIT_COUNT))

          if [ "$MISSING" -le 0 ]; then
            echo "No missing commits. Done."
            exit 0
          fi

          for ((i = 0; i < MISSING; i++)); do
            random_string=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 5)
            new_line="[${random_string}] Praise the Omnissiah!"
            echo "$new_line" >> book.txt
            git add book.txt
            git commit -m "$new_line"
          done

      - name: Push commits
        env:
          JUNIOR_TOKEN: ${{ secrets.JUNIOR_TOKEN }}
        run: |
          echo "Pushing commits..."
          git push https://x-access-token:$JUNIOR_TOKEN@github.com/${{ github.repository }}.git
